### PR TITLE
[MinorVersion] Added chat profanity filter

### PR DESCRIPTION
**Pull request by MChambers1992**
Added functionality to have certain words filtered in the chat window if the developer has profanity filter set to true. Using the lightweight swearjar (https://www.npmjs.com/package/swearjar) package. 

Also removed empty descriptor parameters from chat as they serve no purpose other than to bloat the file size, fields are descriptive enough without these header breaks in params.

### CODE REVIEW

**Comment by Nelderson** [comment]
I love the idea of the swear jar!  I think I even mentioned it in one of my videos.  

My only concern is placing this config on the client side instead of a separate config file on the server.  All someone would have to do is go into the plugin.js file and switch the boolean to false and be able to swear away.  If the config is purely on the server it's much more secure.

And thank you again for the support and suggestions for the system!  I do greatly appreciate anybody willing to put time and effort into my projects.

**Comment by Yoshi72** [comment]
Most profanity filters usually work only client side. Thought they do it it optionally for _receiving_ messages. I don't think that applying the filter before sending it is a good idea. As Nelderson mentioned, it's too easy to go around that and the server only receives the already filtered message. Maybe the Server host wants to log all the chat messages in their original form (e.g. to check if someone is really offending someone else).

It's best to apply the filter either server side when sending it or by the client when receiving the message. The latter is the better choice as this allows the players to disable the profanity filter manually on their side without affecting other player.

**Comment by MChambers1992** [comment]
Yeah I had considered the pros and cons of doing it both ways but had initially considered handling it on the server the better option. Totally agree with the points raised thinking about it now though, I can look into moving this entirely to the client side so it is a toggleable player feature if people think it is still worth including?

**Comment by Yoshi72** [comment]
It certainly is. In fact, I think for for an online RPG Maker chat system it's kinda mandatory, as there are probably many underaged or other kind of people that need this kind of "protection".

Thought maybe we can have a server sided filtering as an option?

**Comment by MChambers1992** [comment]
We could add a hard config option to the server so that all chat is either filtered by swearjar or not without requiring the client to send the profanityFilter flag whilst also adding something like https://github.com/ChaseFlorell/jQuery.ProfanityFilter into the client side and having it available on a per player basis through an options menu? I think this solution would probably give the most control to developers with regards to which solution they prefer. 

If people agree I can update the PR with the proposed solution.

**Comment by Yoshi72** [comment]
That's what I was trying to suggest. Give an option for the server to filter all messages regardless of client options and give a client option to filter displayed messages only for the specific client.

**Comment by Nelderson** [comment]
You could make it configurable per person, but as a game developer if I'm making a game for a general audience I don't want a kid to be able to turn on profanity because they feel like it.  On the other hand if you're making a more mature game I don't see the huge issue with either just banning profanity or letting it go...unless the profanity offends you......

If you want to go nuts with the configuration on the client side as well in like the options menu that's fine, but for me to accept the pull request I certainly want to see it controlled purely on the server for security reasons.

**Comment by MChambers1992** [comment]
Fair points @Nelderson. I've updated the PR to be handled entirely on the server side.

**Pull request merged**
