### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by shadowoffice**
Small update

### CODE REVIEW

**Comment by MChambers1992** [comment]
Looks good to me :shipit:

**Comment by shadowoffice** [comment]
you have idea what can code now XD ??

**Comment by MChambers1992** [comment]
Got a few ideas for things we can do, ideally we need a better place to discuss the project roadmap or even if that will be a thing. Most of the direction comes from @Nelderson but if we are wanting to take this in the direction of a proper open-source project it would be better to get a roadmap sorted.

Any suggestions on where we could discuss?

**Comment by shadowoffice** [comment]
Nelderson can make discord for this 👍

**Comment by Nelderson** [comment]
I'll make a Discord server later on today 👍

**Comment by Nelderson** [comment]
I can't speak to how often I'll be available, but here's the link for the Discord server:

https://discord.gg/b4F8CRW

I'll throw this on the main Readme later on this week

**Comment by shadowoffice** [comment]
@MChambers1992 coming to on server 👍

**Pull request merged**
