### PR TITLE
Client script bug fixes and chat server logging

### PR DESCRIPTION
**Pull request by Yoshi72**
- You can now enable logging of chat messages on the server. This is can be enabled via configuration file.
- Online_Network_Players now syncs moveSpeed and moveFrequenzy properly. Network players should now move properly.
- Bug fixes and changes to Online_Login_Core
- - It now completely replaces Title_Screen by default
- - added a new feature to enable the Title Screen, but replaces the "New Game" and "Continue" command with a "Login" command
- - Completely disables Saving if either of the Title Screen changes are active
- - New startGame() function for MMO_Scene_Title. This makes it easier to modify with other scripts/plugins

Known Bugs: 
- The Login screen only works on the first call. If you start it a second time, no login form will pop up and the game will stuck.
- MMO_Title_Screen is defined inside a scope and thus hidden for other scripts. Gonna fix this with the next commit.

Note: I apologize for completely overwriting the formatting of Online_Login_Core. I didn't meant to. I know that it makes comparing the changes much more difficult.

### CODE REVIEW

**Comment by Yoshi72** [comment]
I've noticed another "bug" in the login screen script.
Since MMO_Title_screen is defined inside the scope, you can't access it with another plugin. This also means that the function I added to the script startGame() isn't accessable to other scripts either.

Moving the initalization of the class outside the scope easily fixes the problem.

**Comment by Nelderson** [comment]
After reviewing the code for the Online_Login_Core I cannot merge this pull request into the main release.  I want to give you credit for the Netplayer and Chat changes that you made.  If you can take off the Login Core changes from your pull request then I will be glad to add the other changes.

**Comment by Yoshi72** [comment]
There we go... It looks like I somehow managed to remove the commit for the login screen.
Could you tell me why you couldn't approve of the Login Core changes?

**Comment by Nelderson** [comment]
These are a couple reasons off the top of my head since the file itself is now off github:

1. Overwriting the Title Scene - I plan on using the regular Title screen in the future after login so that things like cloud saving can be implemented easier (Load screen). 
2. Disabled save - While this will work for most games it overwrites too much and people might want to be able to save locally in their game.

If you have any other questions or suggestions let me know!  I really appreciate the fact you contributed to this project, and want to sincerely thank you.

**Pull request merged**
